#!/bin/sh
# requires https://metacpan.org/pod/Regexp::Common::URI
[ -f "$1" ] && { setsid -f xdg-open "$1"; exit ;}
url="$(echo "$1" | perl -M'Regexp::Common=URI' -ne 'if (/($RE{URI})/) {print $1; exit}')"
[ -n "$url" ] && { setsid -f "${BROWSER:-xdg-open}" "$url"; exit ;}
notify-send -t 2000 -u critical st-plumber "Selection is not a valid file or url!"
